# Generated by Django 5.2.7 on 2025-11-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorSummary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('zenodo_name', models.TextField(null=True)),
                ('github_name', models.TextField(null=True)),
                ('orcid', models.TextField(null=True)),
                ('h_index', models.IntegerField(null=True)),
                ('i10_index', models.IntegerField(null=True)),
                ('n_citas', models.IntegerField(null=True)),
                ('n_publicaciones', models.IntegerField(null=True)),
                ('n_publicaciones_oa', models.IntegerField(null=True)),
                ('publicaciones_citas_avrg', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'author_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author_id', models.IntegerField()),
                ('type', models.TextField(null=True)),
                ('doi', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('published_in', models.TextField(null=True)),
                ('authors', models.TextField(null=True)),
                ('year', models.TextField(null=True)),
                ('cited_by', models.IntegerField(null=True)),
                ('api_source', models.TextField(null=True)),
                ('wikipedia_mentions', models.IntegerField(null=True)),
                ('newsfeed_mentions', models.IntegerField(null=True)),
                ('authors_institutions', models.TextField(null=True)),
                ('institutions_country_code', models.TextField(null=True)),
            ],
            options={
                'db_table': 'works',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('percent', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('result_author_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('celery_id', models.CharField(blank=True, db_index=True, help_text='ID de la tarea de Celery (task_id).', max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'job',
                'managed': True,
            },
        ),
    ]
