# Generated by Django 5.2.7 on 2025-11-03 19:59
#
# UPDATED:
# - Makes this migration idempotent (safe to run even if celery_id already exists).
# - Compatible with PostgreSQL (production) and SQLite (dev).
#
# Context:
#   profiles.0001_add_celery_id already adds the `celery_id` column.
#   The previous version of this migration added it again with raw SQL,
#   which fails on PostgreSQL with "column already exists".

from django.db import migrations


def _column_exists_postgres(cursor, table: str, column: str) -> bool:
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = %s AND column_name = %s
        """,
        [table, column],
    )
    return cursor.fetchone() is not None


def _column_exists_sqlite(cursor, table: str, column: str) -> bool:
    cursor.execute(f"PRAGMA table_info({table});")
    return any(row[1] == column for row in cursor.fetchall())


def forwards(apps, schema_editor):
    """Ensure celery_id exists and indexes are created (safe to re-run)."""

    Job = apps.get_model("profiles", "Job")
    table = Job._meta.db_table  # respects db_table if you set it
    vendor = schema_editor.connection.vendor
    column = "celery_id"

    # 1) Ensure the column exists (backend-specific check)
    if vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            if not _column_exists_postgres(cursor, table, column):
                schema_editor.execute(f'ALTER TABLE "{table}" ADD COLUMN {column} varchar(255);')

    elif vendor == "sqlite":
        with schema_editor.connection.cursor() as cursor:
            if not _column_exists_sqlite(cursor, table, column):
                schema_editor.execute(f"ALTER TABLE {table} ADD COLUMN {column} varchar(255);")

    else:
        # Unknown backend: do nothing to avoid breaking deployments unexpectedly.
        return

    # 2) Ensure indexes exist (IF NOT EXISTS works on PostgreSQL and SQLite)
    schema_editor.execute(
        f'CREATE INDEX IF NOT EXISTS idx_job_celery_id ON "{table}" ({column});'
    )
    schema_editor.execute(
        f'CREATE UNIQUE INDEX IF NOT EXISTS uniq_job_celery_id ON "{table}" ({column});'
    )


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_add_celery_id"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
