# Generated by Django (custom)
# Updated to be SAFE with PostgreSQL: this migration only runs on SQLite.
#
# Why:
# - The original migration contains SQLite-only statements (PRAGMA, AUTOINCREMENT, GLOB).
# - When you run the project on PostgreSQL (your Docker production-like setup), those statements crash.
#
# Behaviour:
# - If database vendor is NOT SQLite -> NO-OP (does nothing).
# - If database vendor IS SQLite -> runs the original SQL using executescript (or a safe fallback).

from django.db import migrations

SQL = r"""
PRAGMA foreign_keys=off;

-- 1) Create the new table with autoincrement PK
CREATE TABLE __job_new (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'pending',
    percent integer NOT NULL DEFAULT 0,
    error text NULL,
    result_author_id integer NULL,
    created_at datetime NOT NULL,
    finished_at datetime NULL,
    celery_id varchar(255) NULL
);

-- 2) Copy rows with numeric id (preserve id)
INSERT INTO __job_new (id, status, percent, error, result_author_id, created_at, finished_at, celery_id)
SELECT CAST(id AS INTEGER), status, percent, error, result_author_id, created_at, finished_at, celery_id
FROM job
WHERE id GLOB '[0-9]*' AND id IS NOT NULL AND TRIM(id) <> '';

-- 3) Copy rows with non-numeric / empty id (SQLite assigns a new id)
INSERT INTO __job_new (status, percent, error, result_author_id, created_at, finished_at, celery_id)
SELECT status, percent, error, result_author_id, created_at, finished_at, celery_id
FROM job
WHERE NOT (id GLOB '[0-9]*' AND id IS NOT NULL AND TRIM(id) <> '');

-- 4) Swap tables
DROP TABLE job;
ALTER TABLE __job_new RENAME TO job;

-- 5) Indexes
CREATE INDEX IF NOT EXISTS idx_job_celery_id ON job (celery_id);

-- If you are sure there are NO duplicates in celery_id, you can enable:
-- CREATE UNIQUE INDEX IF NOT EXISTS uniq_job_celery_id ON job (celery_id);

PRAGMA foreign_keys=on;
"""


def forwards(apps, schema_editor):
    # Only apply on SQLite.
    if schema_editor.connection.vendor != "sqlite":
        return

    with schema_editor.connection.cursor() as cursor:
        # SQLite cursor supports executescript; prefer it to preserve PRAGMA + multi-statement behaviour.
        if hasattr(cursor, "executescript"):
            cursor.executescript(SQL)
        else:
            # Fallback: execute statements one by one.
            for stmt in [s.strip() for s in SQL.split(";")]:
                if stmt:
                    cursor.execute(stmt + ";")


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_sync_db_add_celeryid"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
