# Generated by Django 5.2.7 on 2025-11-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_fix_job_pk_sqlite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(default="pending", max_length=255),
        ),
    ]
