# Generated by Django 5.2.7 on 2025-11-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_expand_job_status_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyVisitorsSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(unique=True)),
                ("unique_visitors", models.IntegerField()),
                ("total_visitors", models.IntegerField()),
            ],
            options={
                "db_table": "daily_visitors_summary",
                "managed": True,
            },
        ),
    ]
